spring:
  application:
    name: practice

server:
  port: 8080

#?? ????? ?? ??
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    #?? ?? ????? ?? ?? ?? ??
    health:
      show-details: always
    # ? ??? /actuator/health ??????? ?? ?? ??? ?? ??? ????? ?????. ?????, ?? ?? ?????? ??? ?? ??? ????, ?? ??? ???? ????.
    prometheus:
      enabled: true