version: '3.7'

services:
  mysql:
    image: ubuntu/mysql:edge
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=msa_exam
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
  
  redis:
    image: redis
    container_name: redis
    restart: always
    environment:
      REDIS_ARGS: "--requirepass systempass"
    ports:
      - 6379:6379

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    restart: always